version: '3.3'
services:
  node:
    build: 
      context: .
      dockerfile: ./environments/Dockerfile.qrlnode
    environment:
      - BOOT_PHASE=${BOOT_PHASE}
      - DOCKER_UID=${DOCKER_UID}
      - DOCKER_GID=${DOCKER_GID}
    image: qrlnode_master
    # ports:
    # - "127.0.0.1:28001:18888"
    # - "127.0.0.1:22001:12000"
    # - "127.0.0.1:27001:18080"
    volumes:
    - ./testnet_vols:/testnet_vols
    - ./scripts:/root/scripts
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
